// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:8575ca54-f007-4fc4-b574-73e8547e3dc2",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_k4QIxMjqc",
    "aws_user_pools_web_client_id": "7s4pmt7nben2ldbs8a4rael2mk",
    "oauth": {},
    "aws_user_files_s3_bucket": "sample-vue-project-bucket-work",
    "aws_user_files_s3_bucket_region": "ap-northeast-1", 
    "aws_appsync_graphqlEndpoint": "https://alcobs3s65as5mboez7swwzlyu.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    //"aws_appsync_authenticationType": "API_KEY",
    //"aws_appsync_apiKey": "da2-zcpxv5dkprh7lnz7sqfsqx5jnu"
};


export default awsmobile;
